apps/users/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    
    path('login-user/',views.LoginUser.as_view(),name='login'),
    path('registrar-vendedor/',views.VendedorRegisterView.as_view(),name='registrar-vendedor'),
    path('registrar-veterinario/',views.VeterinarioRegisterView.as_view(),name='registrar-veterinario'),
    path('registrar-admin/',views.AdminRegisterView.as_view(),name='registrar-admin'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    
    path('administrador/',views.ListViewAdministrador.as_view(),name='administrador'),
    path('registrarUsuariosHome/',views.HomeRegistrarUsuarios.as_view(),name='registrarUsuariosHome'),
    path('home-listado/',views.HomeVerUsuarios.as_view(),name='homeListado'),

    path('ver-admins/',views.ListViewVerAdmins.as_view(),name='verAdmins'),
    path('actualizar-admins/<pk>/',views.AdminUpdateView.as_view(),name='actualizarAdmins'),
    path('eliminar-admins/<pk>/',views.AdminDeleteView.as_view(),name='eliminarAdmins'),

    path('ver-vendedor/',views.ListViewVerVendedores.as_view(),name='verVendedor'),
    path('actualizar-vendedor/<pk>/',views.VendedorUpdateView.as_view(),name='actualizarVendedor'),
    path('eliminar-vendedor/<pk>/',views.VendedorDeleteView.as_view(),name='eliminarVendedor'),

    path('ver-veterinario/',views.ListViewVerVeterinario.as_view(),name='verVeterinario'),
    path('actualizar-veterinario/<pk>/',views.VeterinarioUpdateView.as_view(),name='actualizarVeterinario'),
    path('eliminar-veterinario/<pk>/',views.VeterinarioDeleteView.as_view(),name='eliminarVeterinario'),

    path('reporteUsuarios/',views.ListViewReporteUsuarios.as_view(),name='reporteUsuarios'),
]

apps/ventas/urls.py
from django.urls import path
from . import views

app_name = 'ventas_app'
urlpatterns = [
    path('inventario/',views.ListaProductosViewTrg.as_view(),name='ventas'),
    path('formulario/',views.ProductoCreateView.as_view(),name='formulario'),
    path('facturas/',views.FacturasView.as_view(),name='facturas'),
    path('update/<pk>/',views.ProductoUpdateView.as_view(),name='update'),
    path('delete/<pk>/',views.ProductoDeleteView.as_view(),name='delete'),

    path('add-to-cart-<int:pro_id>/',views.AgregarAlCarro.as_view(),name='agregarCarro'),
    path('my-cart/',views.CarroView.as_view(),name='MiCarro'),
    path('editar-carro/<int:cp_id>/',views.EditarCarroView.as_view(),name='EditarCarro'),
    path('empty-car/',views.VaciarCarroView.as_view(),name='VaciarCarro'),

    path('facturacion/',views.FacturacionView.as_view(),name='Facturacion'),

    path('reporte1pdf/',views.Reporte10PMV.as_view(),name='reporteUnoPDF'),
    path('reporte2pdf/',views.Reporte10PMC.as_view(),name='reporteDosPDF'),
    path('reporte3pdf/',views.ReporteRangoFechas.as_view(),name='reporteTres'),
]

veterinariaApp/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls import handler403
from apps.ventas.views import Error403View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.veterinario.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('user/',include('apps.users.urls')),
]

#Manejo de errores
handler403 = Error403View.as_view()

templates/administrador/actualizar_admin.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/TapBarFormularios.css' %}">
<link rel="stylesheet" href="{% static 'styles/Administrador/form_admin.css' %}">

<div class="tab">
            
    <div class="contenedor">
    
    <div class="center">

        <form method="post">
            {% csrf_token %}
            <div class="titulo">

            <h1>Actualizar Administrador</h1>    
            </div>
            <div class="campos">
                <div class="c1">
                    <div class="espacio">
                        <label >Cedula</label>
                        {{ form.cedula }}
                    </div>
                    
                    <div class="espacio">
                        <label>Nombre</label>
                        {{ form.nombre }}    
                    </div>
                    
                    <div class="espacio">
                        <label>Apellido</label>
                        {{ form.apellidos }}
                    </div>
                </div>
                <div class="c1">
                    <div class="espacio">
                        <label>Edad</label>
                        {{ form.edad }}
                    </div>
                    
                    <div class="espacio">
                        <label>Sexo</label>
                        {{ form.sexo }}
                    </div>
                    
                    <div class="espacio">
                        <label>Telefono</label>
                        {{ form.telefono }}
                    </div>
                    
                </div>
            </div>
            <div class="campos">
                <div class="c1">
                        <div class="espacio">
                            <label >Correo Electronico</label>
                            {{ form.correo }}
                        </div>
                        <div class="espacio">
                            <label>Fecha Ingreso</label>
                            {{ form.fecha_ingreso }}
                        </div>
                        {% for i in form.errors %} {{i}} {% endfor %} 
                        {% if form.errors %}
                            <p>error!</p>
                        {% endif %}
                </div>  
                <div class="c2">
                    <button class="boton" type="submit">Actualizar</button>
                </div>  
            </div>
            
            
        </form>
        
    </div>
</div>

</div>

{% endblock content %}

templates/administrador/actualizar_vendedor.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/TapBarFormularios.css' %}">
<link rel="stylesheet" href="{% static 'styles/Administrador/form_admin.css' %}">

<div class="tab">
            
    <div class="contenedor">
    
    <div class="center">

        <form method="post">
            {% csrf_token %}
            <div class="titulo">

            <h1>Actualizar Vendedor</h1>    
            </div>
            <div class="campos">
                <div class="c1">
                    <div class="espacio">
                        <label >Cedula</label>
                        {{ form.cedula }}
                    </div>
                    
                    <div class="espacio">
                        <label>Nombre</label>
                        {{ form.nombre }}    
                    </div>
                    
                    <div class="espacio">
                        <label>Apellido</label>
                        {{ form.apellidos }}
                    </div>
                </div>
                <div class="c1">
                    <div class="espacio">
                        <label>Edad</label>
                        {{ form.edad }}
                    </div>
                    
                    <div class="espacio">
                        <label>Sexo</label>
                        {{ form.sexo }}
                    </div>
                    
                    <div class="espacio">
                        <label>Telefono</label>
                        {{ form.telefono }}
                    </div>
                    
                </div>
            </div>
            <div class="campos">
                <div class="c1">
                        <div class="espacio">
                            <label >Correo Electronico</label>
                            {{ form.correo }}
                        </div>
                        <div class="espacio">
                            <label>Fecha Ingreso</label>
                            {{ form.fecha_ingreso }}
                        </div>
                        {% for i in form.errors %} {{i}} {% endfor %} 
                        {% if form.errors %}
                            <p>error!</p>
                        {% endif %}
                </div>  
                <div class="c2">
                    <button class="boton" type="submit">Actualizar</button>
                </div>  
            </div>
            
        </form>
        
    </div>
</div>

</div>

{% endblock content %}

templates/administrador/actualizar_veterinario.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/TapBarFormularios.css' %}">
<link rel="stylesheet" href="{% static 'styles/Administrador/form_admin.css' %}">

<div class="tab">
            
    <div class="contenedor">
    
    <div class="center">

        <form method="post">
            {% csrf_token %}
            <div class="titulo">

            <h1>Actualizar Veterinario</h1>    
            </div>
            <div class="campos">
                <div class="c1">
                    <div class="espacio">
                        <label >Cedula</label>
                        {{ form.cedula }}
                    </div>
                    
                    <div class="espacio">
                        <label>Nombre</label>
                        {{ form.nombre }}    
                    </div>
                    
                    <div class="espacio">
                        <label>Apellido</label>
                        {{ form.apellidos }}
                    </div>
                </div>
                <div class="c1">
                    <div class="espacio">
                        <label>Edad</label>
                        {{ form.edad }}
                    </div>
                    
                    <div class="espacio">
                        <label>Sexo</label>
                        {{ form.sexo }}
                    </div>
                    
                    <div class="espacio">
                        <label>Telefono</label>
                        {{ form.telefono }}
                    </div>
                    <div class="espacio">
                        <label>Titulo</label>
                        {{ form.titulo }}
                    </div>
                    
                </div>
            </div>
            <div class="campos">
                <div class="c1">
                        <div class="espacio">
                            <label >Correo Electronico</label>
                            {{ form.correo }}
                        </div>
                        <div class="espacio">
                            <label>Fecha Ingreso</label>
                            {{ form.fecha_ingreso }}
                        </div>
                        {% for i in form.errors %} {{i}} {% endfor %} 
                        {% if form.errors %}
                            <p>error!</p>
                        {% endif %}
                </div>  
                <div class="c2">
                    <button class="boton" type="submit">Actualizar</button>
                </div>  
            </div>
            
            
        </form>
        
    </div>
</div>

</div>

{% endblock content %}

templates/administrador/admin_admin.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/TapBarFormularios.css' %}">
<link rel="stylesheet" href="{% static 'styles/Administrador/form_admin.css' %}">

<div class="tab">
            
    <div class="contenedor">
    
    <div class="center">
        

        <form method="post">
            {% csrf_token %}
            <div class="titulo">
            <h1>Registrar Administrador</h1>    
            </div>

            {% if messages %}
            <div class="mensaje_exitoso">
                {% for m in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
                {% endfor %}
            </div>
            {% endif %}

            <div class="campos">
                <div class="c1">
                    <div class="espacio">
                        <label >Cedula</label>
                        {{ form.cedula }}
                    </div>
                    
                    <div class="espacio">
                        <label>Nombre</label>
                        {{ form.nombre }}    
                    </div>
                    
                    <div class="espacio">
                        <label>Apellido</label>
                        {{ form.apellidos }}
                    </div>
                </div>
                <div class="c1">
                    <div class="espacio">
                        <label>Edad</label>
                        {{ form.edad }}
                    </div>
                    
                    <div class="espacio">
                        <label>Sexo</label>
                        {{ form.sexo }}
                    </div>
                    
                    <div class="espacio">
                        <label>Telefono</label>
                        {{ form.telefono }}
                    </div>
                    
                </div>
            </div>
            <div class="campos">
                <div class="c1">
                        <div class="espacio">
                            <label >Correo Electronico</label>
                            {{ form.correo }}
                        </div>
                        <div class="espacio">
                            <label>Contraseña</label>
                            {{ form.password1 }}
                        </div>
                        <div class="espacio">
                            <label>Repetir Contraseña</label>
                            {{ form.password2 }}
                        </div>
                        <div class="espacio">
                            <label>Fecha Ingreso</label>
                            {{ form.fecha_ingreso }}
                        </div>
                        
                        {% if form.errors %}
                            <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                            <script src="/static/scripts/sweetAlert.js"></script>
                          {% endif %}
                </div>  
                <div class="c2">
                    <button class="boton" type="submit"> Registrar</button>
                </div> 
                
            </div>
            
            {% if form.non_field_errors %}
            <div class="alert1">
            <img id="alet" src="/static/assets/alert.png"><h4 id="mensajeE">{{ form.non_field_errors }}</h4>
              
              
            </div>
            {% endif %}
            
        </form>
        
    </div>
    
</div>


</div>
{% endblock content %}

templates/administrador/home-registrar.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/botones.css' %}">
<div class="contenedor">

        <div class="contenedor-botones">
            <a href="{% url 'user_app:registrar-vendedor' %}" class="boton"><b>Registrar Vendedor</b></a>
            <a href="{% url 'user_app:registrar-veterinario' %}" class="boton"><b>Registrar Veterinario</b></a>
            <a href="{% url 'user_app:registrar-admin' %}" class="boton"><b>Registrar Administrador</b></a>
        </div>
    </div>

{% endblock content %}

templates/administrador/home.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/botones.css' %}">


        
<a href="{% url 'user_app:registrarUsuariosHome' %}" class="boton"><b>Registrar Usuario</b></a>
<a href="{% url 'user_app:homeListado' %}" class="boton"><b>Ver Tablas Usuarios</b></a>
<a href="{% url 'user_app:reporteUsuarios' %}" class="boton"><b>Reporte Usuario</b></a>


{% endblock content %}

templates/administrador/listado_usuarios_home.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/botones.css' %}">
<div class="contenedor">

        <div class="contenedor-botones">
            <a href="{% url 'user_app:verAdmins' %}" class="boton"><b>Listado administradores</b></a>
            <a href="{% url 'user_app:verVendedor' %}" class="boton"><b>Listado Vendedores</b></a>
            <a href="{% url 'user_app:verVeterinario' %}" class="boton"><b>Listado Veterinarios</b></a>
        </div>
    </div>

{% endblock content %}

templates/administrador/reporteAdmin.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/Administrador/botones.css' %}">
<div class="contenedor">

        <div class="contenedor-botones">
            <a href="{% url 'ventas_app:reporteUnoPDF' %}" class="boton"><b>Reporte 10 productos mas vendidos</b></a>
            <a href="{% url 'ventas_app:reporteDosPDF' %}" class="boton"><b>Reporte clientes con mayor facturacion</b></a>
            <a href="{% url 'ventas_app:reporteTres' %}" class="boton"><b>Reporte ventas por rango de fechas</b></a>
        </div>
    </div>

{% endblock content %}

templates/administrador/verAdmins.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/ventas.css' %}">
  <script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Lista de Administradores</h2>
    </section>
    <form method="get">
    <div class="buscar">
        {% csrf_token %}
        <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese la cedula">
        <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
      </div>
    </form>
    <br>
    <br>
     <table>
       <thead>
         <tr class="propiedad">
            <th>Cedula</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th>Sexo</th>
            <th>Telefono</th> 
            <th>Fecha Ingreso</th>  
            <th>Correo Electronico</th> 
          </tr>
        </thead>
        <tbody>
          
          {% for a in object_list %}
          <tr id="valores">
            <td>{{ a.cedula|truncatechars:20 }}</td>
            <td>{{ a.nombre|truncatechars:20 }}</td>
            <td>{{ a.apellidos|truncatechars:20 }}</td>
            <td>{{ a.edad|truncatechars:20 }}</td>
            <td>{{ a.sexo }}</td>
            <td>{{ a.telefono }}</td> 
            <td>{{ a.fecha_ingreso }}</td> 
            <td>{{ a.correo }}</td>  
            <td>
              <a class="fa-solid fa-crop" href="{% url 'user_app:actualizarAdmins' a.id %}"></a>
              <a class="fa-regular fa-trash-can" href="javascript:abrir()"></a>
            </td>
          </tr>
          
          
            <div class="Ventanae" id="elimi">
              <form action="{% url 'user_app:eliminarAdmins' a.id %}" method="post">
                {% csrf_token %}
                <h3>¿Quiere eliminar este administrador? </h3>
                <h3>{{ a.nombre }}</h3>
                <h3>confirme que desea realizar</p>
                  <br>
                  <button type="submit" id="Confirmar">Confirmar</button>
                </form>
                <button id="cancelar" onclick="cerrar()"> Cancelar</button>
            </div>

            {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>

            
          {% endfor %}
        </tbody>
      </table>
      <script src="{% static 'scripts/ventas.js' %}"></script>

      <!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
    
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><b>&laquo;</b></a>  
    {% endif %}
    
    {% for pagina in paginator.page_range %}
    {% if pagina == page_obj.number  %}
    <a class="active" href="?page={{ pagina }}"><b>{{ pagina }}</b></a>
    {% else %}
    <a href="?page={{ pagina }}"><b>{{ pagina }}</b></a> 
    {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><b>&raquo;</b></a>   
    {% endif %}
    
    {% endif %}
    
  </div>
</div>
  <!-- FIN bloque de paginacion -->
  
  
  
{% endblock content %}
      

templates/administrador/verVendedor.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/ventas.css' %}">
  <script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Lista de Vendedores</h2>
    </section>
    <form method="get">
    <div class="buscar">
        {% csrf_token %}
        <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese la cedula">
        <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
      </div>
    </form>
    <br>
    <br>
     <table>
       <thead>
         <tr class="propiedad">
            <th>Cedula</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th>Sexo</th>
            <th>Telefono</th> 
            <th>Fecha Ingreso</th>  
            <th>Correo Electronico</th> 
          </tr>
        </thead>
        <tbody>
          
          {% for v in object_list %}
          <tr id="valores">
            <td>{{ v.cedula|truncatechars:20 }}</td>
            <td>{{ v.nombre|truncatechars:20 }}</td>
            <td>{{ v.apellidos|truncatechars:20 }}</td>
            <td>{{ v.edad|truncatechars:20 }}</td>
            <td>{{ v.sexo }}</td>
            <td>{{ v.telefono }}</td> 
            <td>{{ v.fecha_ingreso }}</td> 
            <td>{{ v.correo }}</td>  
            <td>
              <a class="fa-solid fa-crop" href="{% url 'user_app:actualizarVendedor' v.id %}"></a>
              <a class="fa-regular fa-trash-can" href="javascript:abrir()"></a>
            </td>
          </tr>
          
          
            <div class="Ventanae" id="elimi">
              <form action="{% url 'user_app:eliminarVendedor' v.id %}" method="post">
                {% csrf_token %}
                <h3>¿Quiere eliminar este vendedor? </h3>
                <h3>{{ v.nombre }}</h3>
                <h3>confirme que desea realizar</p>
                  <br>
                  <button type="submit" id="Confirmar">Confirmar</button>
                </form>
                <button id="cancelar" onclick="cerrar()"> Cancelar</button>
            </div>

            {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>

            
          {% endfor %}
        </tbody>
      </table>
      <script src="{% static 'scripts/ventas.js' %}"></script>

      <!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
    
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>  
    {% endif %}
    
    {% for pagina in paginator.page_range %}
    {% if pagina == page_obj.number  %}
    <a class="active" href="?page={{ pagina }}">{{ pagina }}</a>
    {% else %}
    <a href="?page={{ pagina }}">{{ pagina }}</a> 
    {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>   
    {% endif %}
    
    {% endif %}
    
  </div>
</div>
  <!-- FIN bloque de paginacion -->
  
  
  
{% endblock content %}
      

templates/administrador/verVeterinario.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/ventas.css' %}">
  <script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Lista de Veterinarios</h2>
    </section>
    <form method="get">
    <div class="buscar">
        {% csrf_token %}
        <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese la cedula">
        <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
      </div>
    </form>
    <br>
    <br>
     <table>
       <thead>
         <tr class="propiedad">
            <th>Cedula</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th>Sexo</th>
            <th>Telefono</th> 
            <th>Fecha Ingreso</th>  
            <th>Correo Electronico</th>
            <th>Titulo</th>  
          </tr>
        </thead>
        <tbody>
          
          {% for v in object_list %}
          <tr id="valores">
            <td>{{ v.cedula|truncatechars:20 }}</td>
            <td>{{ v.nombre|truncatechars:20 }}</td>
            <td>{{ v.apellidos|truncatechars:20 }}</td>
            <td>{{ v.edad|truncatechars:20 }}</td>
            <td>{{ v.sexo }}</td>
            <td>{{ v.telefono }}</td> 
            <td>{{ v.fecha_ingreso }}</td> 
            <td>{{ v.correo }}</td>
            <td>{{ v.titulo }}</td>    
            <td>
              <a class="fa-solid fa-crop" href="{% url 'user_app:actualizarVeterinario' v.id %}"></a>
              <a class="fa-regular fa-trash-can" href="javascript:abrir()"></a>
            </td>
          </tr>
          
          
            <div class="Ventanae" id="elimi">
              <form action="{% url 'user_app:eliminarVeterinario' v.id %}" method="post">
                {% csrf_token %}
                <h3>¿Quiere eliminar este veterinario? </h3>
                <h3>{{ v.nombre }}</h3>
                <h3>confirme que desea realizar</p>
                  <br>
                  <button type="submit" id="Confirmar">Confirmar</button>
                </form>
                <button id="cancelar" onclick="cerrar()"> Cancelar</button>
            </div>

            {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>

            
          {% endfor %}
        </tbody>
      </table>
      <script src="{% static 'scripts/ventas.js' %}"></script>

      <!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
    
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>  
    {% endif %}
    
    {% for pagina in paginator.page_range %}
    {% if pagina == page_obj.number  %}
    <a class="active" href="?page={{ pagina }}">{{ pagina }}</a>
    {% else %}
    <a href="?page={{ pagina }}">{{ pagina }}</a> 
    {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>   
    {% endif %}
    
    {% endif %}
    
  </div>
</div>
  <!-- FIN bloque de paginacion -->
  
  
  
{% endblock content %}
      