apps/veterinario/urls.py
from django.urls import path
from . import views

app_name = 'veterinaria_app'
urlpatterns = [
    path('',views.ListViewVeterinario.as_view(),name='home'),
    path('historial/',views.ListViewHistorial.as_view(),name='historial'),
    path('formulario-historial/',views.CreateFormularioHistorial.as_view(),name='formulario-historial'),
    path('inicio-historial/',views.ListViewInicioHistorial.as_view(),name='inicio-historial'),
    path('cliente-responsable/',views.ListViewVerClienteResponsable.as_view(),name='cliente-responsable'),
    path('formulario-cliente/',views.CreateClienteResponsable.as_view(),name='formulario-cliente'),
    path('mascotas/',views.ListViewMascotas.as_view(),name='mascotas'),
    path('formulario-mascota/',views.CreateFormularioMascotas.as_view(),name='formulario-mascota'),
    path('detalle-historial/<pk>/',views.DetailViewHistorial.as_view(),name='detailView'),

]

veterinariaApp/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls import handler403
from apps.ventas.views import Error403View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.veterinario.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('user/',include('apps.users.urls')),
]

#Manejo de errores
handler403 = Error403View.as_view()

templates/historial/cliente-responsable.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Clientes/Responsables{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/cliente-responsable.css' %}">
<script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="clientes">Clientes/Responsables</h2>
       <nav class="btn">
            <a class="agregar" href="{% url 'veterinaria_app:formulario-cliente' %}"><i class="fa-solid fa-plus"></i>Agregar</a>
        </nav>
    </section>
    <form method="get">
      <div class="buscar">
          {% csrf_token %}
          <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese la cedula">
          <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
        </div>
      </form>
    <br>
    <br>
     <table>
      <thead>

        <tr class="propiedad">
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Cedula</th>
          <th>Dirección</th>
          <th>Telefono</th>
          <th>Edad</th>
          <th>Sexo</th>
          <th class="celdaCrud"></th>
        </tr>
      </thead>
      <tbody>

        
        {% for d in object_list %}
        <tr id="valores">
          <td>{{ d.nombre|truncatechars:20 }}</td>
          <td>{{ d.apellidos|truncatechars:20 }}</td>
          <td>{{ d.cedula|truncatechars:20 }}</td>
          <td>{{ d.direccion|truncatechars:20 }}</td>
          <td>{{ d.telefono|truncatechars:20 }}</td>
          <td>{{ d.edad|truncatechars:20 }}</td>
          <td>{{ d.sexo|truncatechars:20 }}</td>
        </tr>


        {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>

        {% endfor %}
      </tbody>
      </table>
      <script src="{% static 'scripts/ventas.js' %}"></script>

      <!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
    
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><b>&laquo;</b></a>  
    {% endif %}
    
    {% for pagina in paginator.page_range %}
    {% if pagina == page_obj.number  %}
    <a class="active" href="?page={{ pagina }}"><b>{{ pagina }}</b></a>
    {% else %}
    <a href="?page={{ pagina }}"><b>{{ pagina }}</b></a> 
    {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><b>&raquo;</b></a>   
    {% endif %}
    
    {% endif %}
    
  </div>
</div>
  <!-- FIN bloque de paginacion -->

      {% endblock content %}

templates/historial/detailView.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<!-- <link rel="stylesheet" href="{% static 'styles/historial.css' %}"> --> 
<link rel="stylesheet" href="/static/styles/detailView.css">

<script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Historial Clinico De {{ historialclinico.mascota }}</h2>
      <div class="content-fondo">
        <div class="formulario">
            <form method="post">
                {% csrf_token %} 

                <div id="formularioHistorial">
                    <h3>1.Datos de la mascota y veterinario:</h3>
                    <div class="campo1">
                        <label>Nombre mascota:</label>
                        {{ historialclinico.mascota }}
                        
                    </div>
                    
                    
                    <div class="campo2">
                        <label>Veterinario:</label>
                        {{ historialclinico.veterinario }}
                    </div>
                    
                    <h3 class="separador">2. Anamnesis:</h3>
                    <div class="areatext">
                      {{ historialclinico.anamnesis }}
                    </div>
                    
                    <div class="campo3">
                        <label>Vacunas:</label>
                        {{ historialclinico.vacunas }}
                    </div>
                    
                    <h3 class="separador">3. Examen fisico:</h3>
                    <div class="areatext">
                        {{ historialclinico.examen_fisico }}
                    </div>

                    <div class="campo4">
                        <label>Peso:</label>
                        {{ historialclinico.peso }}
                    </div>

                    <div class="campo4">
                        <label>Temperatura:</label>
                        {{ historialclinico.temperatura }}
                    </div>

                    <div class="campo4">
                        <label>Frecuencia cardiaca:</label>
                        {{ historialclinico.frecuencia_cardiaca }}
                    </div>

                    <h3 class="separador">4. Detalles de la visita:</h3>
                    <div class="areatext">
                        {{ historialclinico.detalles_visita }}
                    </div>

                    <h3 class="separador">5. Diagnostico:</h3>
                    <div class="areatext">
                        {{ historialclinico.diagnostico }}
                    </div>

                    <h3 class="separador">6. Patología:</h3>
                    <div class="areatext">
                        {{ historialclinico.patologia }}
                    </div>

                    <h3 class="separador">7. Tratamiento:</h3>
                    <div class="areatext">
                        {{ historialclinico.tratamiento }}
                    </div>
                </div>

                {% for i in form.errors %} {{i}} {% endfor %} 
                {% if form.errors %}
                <p>error!</p>
                {% endif %}

            
            </form>
        </div>

    </div>
    </section>
    
    
{% endblock content %}

templates/historial/formulario-clientes.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Formulario Clientes/Responsables{% endblock title %}
{% block content %}
<link rel="stylesheet" href="/static/styles/formulario-clientes.css">
<body>
        <div class="content-fondo">
            <div class="formulario">
                <form method="post">
                    <h2 class="titulo">Registrar Cliente/Responsable</h2><br>
                    
                    {% if messages %}
                    <div class="mensaje_exitoso">
                        {% for m in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
                        {% endfor %}
                    </div>
                    {% endif %}

                    {% csrf_token %} 

                    <div id="formularioClienteResponsable">

                        <div class="campo">
                            <label>Nombres</label>
                            {{ form.nombre }}
                        </div>
                        
                        
                        <div class="campo">
                            <label>Apellidos</label>
                            {{ form.apellidos }}
                        </div>
                        
                        <div class="campo">
                            <label>Cedula</label>
                            {{ form.cedula }}
                        </div>
                        
                        <div class="campo">
                            <label>Dirección</label>
                            {{ form.direccion }}
                        </div>
                        
                        <div class="campo">
                            <label>Telefono</label>
                            {{ form.telefono }}
                        </div>
                        <div class="campo">
                            <label>Edad</label>
                            {{ form.edad }}
                        </div>
                        <div class="campo">
                            <label>Sexo</label>
                            {{ form.sexo }}
                        </div>
                        
                    </div>

                    
                    {% if form.errors %}
                    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                        <script src="/static/scripts/sweetAlert.js"></script>
                    {% endif %}
                    <button type="submit" class="btn">Guardar</button>

                    {% if form.non_field_errors %}
                    <div class="alertE" role="alert">
                    <img id="alet" src="/static/assets/alert.png"><h4 id="mensajeE">{{ form.non_field_errors }}</h4>
                    
                    
                    </div>
                    {% endif %}

                    
                </form>
            </div>

            <div class="imagen-content">
                <img class = "imagen" src="/static/assets/responsable.png">
            </div>
        </div>
</body>
<script src="{% static 'scripts/formulariosVenta.js' %}"></script>
{% endblock content %}

templates/historial/formulario-historial.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Formulario Historial Clinico{% endblock title %}
{% block content %}
<link rel="stylesheet" href="/static/styles/formulario-historial.css">
<body>
        <div class="content-fondo">
            <div class="formulario">
                <form method="post">
                    <h2 class="titulo">Registrar Historia Clinica</h2><br>
                    {% csrf_token %} 

                    {% if messages %}
                    <div class="mensaje_exitoso">
                        {% for m in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
                        {% endfor %}
                    </div>
                    {% endif %}

                    <div id="formularioHistorial">
                        <h3>1.Datos de la mascota y veterinario:</h3>
                        <div class="campo1">
                            <label>Nombre mascota</label>
                            {{ form.mascota }}
                        </div>
                        
                        <div class="campo2">
                            <label>Veterinario</label>
                            {{ form.veterinario }}
                        </div>
                        
                        <h3>2. Anamnesis:</h3>
                        <div class="areatext">
                            {{ form.anamnesis }}
                        </div>
                        
                        <div class="campo3">
                            <label>Vacunas</label>
                            {{ form.vacunas }}
                        </div>
                        
                        <h3>3. Examen fisico:</h3>
                        <div class="areatext">
                            {{ form.examen_fisico }}
                        </div>

                        <div class="campo4">
                            <label>Peso</label>
                            {{ form.peso }}
                        </div>

                        <div class="campo4">
                            <label>Temperatura</label>
                            {{ form.temperatura }}
                        </div>

                        <div class="campo4">
                        <label>Frecuencia cardiaca</label>
                            {{ form.frecuencia_cardiaca }}
                        </div>

                        <h3>4. Detalles de la visita:</h3>
                        <div class="areatext">
                            {{ form.detalles_visita }}
                        </div>

                        <h3>5. Diagnostico:</h3>
                        <div class="areatext">
                            {{ form.diagnostico }}
                        </div>

                        <h3>6. Patología:</h3>
                        <div class="areatext">
                            {{ form.patologia }}                                    
                        </div>

                        <h3>7. Tratamiento:</h3>
                        <div class="areatext">
                            {{ form.tratamiento }}
                        </div>
                    </div>

                    
                    {% if form.errors %}
                    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                        <script src="/static/scripts/sweetAlert.js"></script>
                        <div class="alertE" role="alert">
                        <h4 id="mensajeE">Error! {% for i in form.errors %} {{i}} {% endfor %}</h4> 
                      </div>
                    {% endif %}

                    <button type="submit" class="btn">Guardar</button>
                </form>
            </div>

        </div>
</body>
<script src="{% static 'scripts/formulariosVenta.js' %}"></script>
{% endblock content %}

templates/historial/formulario-mascota.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Formulario Mascotas{% endblock title %}
{% block content %}
<link rel="stylesheet" href="/static/styles/formulario-mascota.css">
<body>
        <div class="content-fondo">
            <div class="formulario">
                <form method="post">
                    <h2 class="titulo">Registrar Mascotas</h2><br>

                    {% if messages %}
                    <div class="mensaje_exitoso">
                        {% for m in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
                        {% endfor %}
                    </div>
                    {% endif %}
                    
                    {% csrf_token %} 

                    <div id="formularioClienteResponsable">

                        <div class="campo">
                            <label>Nombre</label>
                            {{ form.nombre }}
                        </div>
                        
                        
                        <div class="campo">
                            <label>Raza</label>
                            {{ form.raza }}
                        </div>
                        
                        <div class="campo">
                            <label>Especie</label>
                            {{ form.especie }}
                        </div>
                        <div class="campo2">
                            <label>Sexo</label>
                            {{ form.sexo }}
                        </div>
                        <div class="campoEdad">
                            <label>Edad</label>
                            {{ form.edad }}
                        </div>

                        <div class="campo">
                            <label>Color</label>
                            {{ form.color }}
                        </div>

                        <div class="campoCastrado">
                            <label>¿Castrado?</label>
                            {{ form.castrado }}
                        </div>

                        <div class="campoCastrado">
                            <label>Estado</label>
                            {{ form.estado }}
                        </div>
                        
                        <div class="campo3">
                            <label>Cedula/Responsable</label>
                            {{ form.duenio }}
                        </div>
                        
                    </div>

                    <button type="submit" class="btn">Guardar</button>

                    
                    {% if form.errors %}
                    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                        <script src="/static/scripts/sweetAlert.js"></script>
                        <div class="alertE" role="alert">
                        <h4 id="mensajeE">Error! {% for i in form.errors %} {{i}} {% endfor %}</h4> 
                      </div>
                    {% endif %}

                    
                </form>
            </div>

            <div class="imagen-content">
                <img class = "imagen" src="/static/assets/pet.png">
            </div>
        </div>
</body>
<script src="{% static 'scripts/formulariosVenta.js' %}"></script>
{% endblock content %}

templates/historial/historial.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/historial.css' %}">
<script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Historial Clinico</h2>
       <nav class="btn">
          <a class="agregar" href="{% url 'veterinaria_app:formulario-historial' %}"><i class="fa-solid fa-plus"></i>Agregar</a>
        </nav>
    </section>
    <form method="get">
      <div class="buscar">
          {% csrf_token %}
          <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese la cedula">
          <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
        </div>
      </form>
      <br>
      <br>
     <table>
      <thead>

        <tr class="propiedad">
          <th>Nombre Mascota</th>
          <th>Veterinario</th>
          <th>Detalles Visita</th>
          <th>Vacunas</th>
          <th>Peso</th>
          <th>Temperatura</th>
          <th>Frecuencia Cardiaca</th>
          <th>Accion</th>
        </tr>
      </thead>
      <tbody>

        {% for h in object_list %}
          
        <tr id="valores">
          <td>{{ h.mascota|truncatechars:10 }}</td>
          <td>{{ h.veterinario|truncatechars:20 }}</td>
          <td>{{ h.detalles_visita|truncatechars:20 }}</td>
          <td>{{ h.vacunas|truncatechars:10 }}</td>
          <td>{{ h.peso|truncatechars:10 }}</td>
          <td>{{ h.temperatura|truncatechars:10 }}</td>
          <td>{{ h.frecuencia_cardiaca|truncatechars:10 }}</td>
          <td>
            <a href="{% url 'veterinaria_app:detailView' h.id %}">Ver</a>
          </td>
        </tr>

        {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>
        {% endfor %}
      </tbody>
       </table>
       <script src="{% static 'scripts/ventas.js' %}"></script>

<!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
  
      {% if is_paginated %}
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}"><b>&laquo;</b></a>  
      {% endif %}
      
      {% for pagina in paginator.page_range %}
      {% if pagina == page_obj.number  %}
      <a class="active" href="?page={{ pagina }}"><b>{{ pagina }}</b></a>
      {% else %}
      <a href="?page={{ pagina }}"><b>{{ pagina }}</b></a> 
      {% endif %}
      {% endfor %}
      
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}"><b>&raquo;</b></a>   
      {% endif %}
      
      {% endif %}
      
    </div>
</div>
  <!-- FIN bloque de paginacion -->

{% endblock content %}

templates/historial/inicio-historial.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Historial Clinico{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/inicio-historial.css' %}">

<a class="gestion" href="{% url 'veterinaria_app:cliente-responsable' %}"><b>Gestionar Clientes/Responsables</b></a>
<a class="gestion" href="{% url 'veterinaria_app:mascotas' %}"><b>Gestionar Mascotas/Pacientes</b></a>
<a class="gestion" href="{% url 'veterinaria_app:historial' %}"><b>Gestionar Historial Clinico</b></a>

{% endblock content %}

templates/historial/mascotas.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Mascotas{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/mascotas.css' %}">
<script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="mascotas">Mascotas</h2>
       <nav class="btn">
            <a class="agregar" href="{% url 'veterinaria_app:formulario-mascota' %}"><i class="fa-solid fa-plus"></i>Agregar</a>
        </nav>
    </section>
    <form method="get">
        <div class="buscar">
            {% csrf_token %}
            <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese la cedula">
            <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
          </div>
        </form>
        <br>
        <br>
    <table>
        <thead>

            <tr class="propiedad">
                <th>Nombre</th>
                <th>Raza</th>
                <th>Especie</th>
                <th>Sexo</th>
                <th>Edad</th>
                <th>Color</th>
                <th>¿Castrado?</th>
                <th>Estado</th>
                <th>Cedula/Responsable</th>
            </tr> 
        </thead>
        <tbody>    
        {% for m in object_list %}
        <tr id="valores">
            <td>{{ m.nombre|truncatechars:20 }}</td>
            <td>{{ m.raza|truncatechars:20 }}</td>
            <td>{{ m.especie|truncatechars:20 }}</td>
            <td>{{ m.sexo|truncatechars:20 }}</td>
            <td>{{ m.edad|truncatechars:20 }}</td>
            <td>{{ m.color|truncatechars:20 }}</td>
            <td>
                {% if m.castrado == True %}
                    <p>Si</p>
                {% else %}
                <p>No</p>
                {% endif %}
            </td>
            <td>{{ m.estado|truncatechars:20 }}</td>
            <td>{{ m.duenio|truncatechars:40 }}</td>
        </tr>


        {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>
        {% endfor %}
            
        </tbody>
    </table>
    <script src="{% static 'scripts/ventas.js' %}"></script>


 <!-- inicio de bloque de paginacion -->
 <div class="center">

    <div class="pagination">
    
        {% if is_paginated %}
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"><b>&laquo;</b></a>  
        {% endif %}
        
        {% for pagina in paginator.page_range %}
        {% if pagina == page_obj.number  %}
        <a class="active" href="?page={{ pagina }}"><b>{{ pagina }}</b></a>
        {% else %}
        <a href="?page={{ pagina }}"><b>{{ pagina }}</b></a> 
        {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"><b>&raquo;</b></a>   
        {% endif %}
        
        {% endif %}
        
      </div>
  </div>
    <!-- FIN bloque de paginacion -->
    
{% endblock content %}