apps/ventas/urls.py
from django.urls import path
from . import views

app_name = 'ventas_app'
urlpatterns = [
    path('inventario/',views.ListaProductosViewTrg.as_view(),name='ventas'),
    path('formulario/',views.ProductoCreateView.as_view(),name='formulario'),
    path('facturas/',views.FacturasView.as_view(),name='facturas'),
    path('update/<pk>/',views.ProductoUpdateView.as_view(),name='update'),
    path('delete/<pk>/',views.ProductoDeleteView.as_view(),name='delete'),

    path('add-to-cart-<int:pro_id>/',views.AgregarAlCarro.as_view(),name='agregarCarro'),
    path('my-cart/',views.CarroView.as_view(),name='MiCarro'),
    path('editar-carro/<int:cp_id>/',views.EditarCarroView.as_view(),name='EditarCarro'),
    path('empty-car/',views.VaciarCarroView.as_view(),name='VaciarCarro'),

    path('facturacion/',views.FacturacionView.as_view(),name='Facturacion'),

    path('reporte1pdf/',views.Reporte10PMV.as_view(),name='reporteUnoPDF'),
    path('reporte2pdf/',views.Reporte10PMC.as_view(),name='reporteDosPDF'),
    path('reporte3pdf/',views.ReporteRangoFechas.as_view(),name='reporteTres'),
]

apps/veterinario/urls.py
from django.urls import path
from . import views

app_name = 'veterinaria_app'
urlpatterns = [
    path('',views.ListViewVeterinario.as_view(),name='home'),
    path('historial/',views.ListViewHistorial.as_view(),name='historial'),
    path('formulario-historial/',views.CreateFormularioHistorial.as_view(),name='formulario-historial'),
    path('inicio-historial/',views.ListViewInicioHistorial.as_view(),name='inicio-historial'),
    path('cliente-responsable/',views.ListViewVerClienteResponsable.as_view(),name='cliente-responsable'),
    path('formulario-cliente/',views.CreateClienteResponsable.as_view(),name='formulario-cliente'),
    path('mascotas/',views.ListViewMascotas.as_view(),name='mascotas'),
    path('formulario-mascota/',views.CreateFormularioMascotas.as_view(),name='formulario-mascota'),
    path('detalle-historial/<pk>/',views.DetailViewHistorial.as_view(),name='detailView'),

]

veterinariaApp/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls import handler403
from apps.ventas.views import Error403View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.veterinario.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('user/',include('apps.users.urls')),
]

#Manejo de errores
handler403 = Error403View.as_view()

apps/ventas/models.py
from django.db import models
from django.urls import reverse

from apps.users.models import Vendedor, Duenio

from .managers import VentasManager

# Create your models here.

class Producto(models.Model):
    identificacion = models.PositiveBigIntegerField('Codigo', unique=True, default=0)
    nombre = models.CharField('Nombre', max_length=50)
    descripcion = models.TextField(null=True)
    precio = models.PositiveIntegerField(default=0)
    iva = models.PositiveIntegerField(default=0)
    stock = models.PositiveIntegerField(default=0)
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE)

    objects = VentasManager()

    class Meta:
        ordering = ['id','nombre']
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
    
   
    def __str__(self):
        return  str(self.id) + ' ' +self.nombre 


class Carro(models.Model):
    cliente = models.ForeignKey(Vendedor, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField()
    created_at = models.DateTimeField('Fecha', auto_now_add=True)

    def __str__(self):
        return "Carro: " + str(self.id) + ' - ' + "Fecha:" + str(self.created_at)


class ProductoCarro(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE,  null=True, blank=True)
    rate = models.PositiveIntegerField()
    cantidad = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Carro: " + str(self.carro.id) + "Producto en carro" + str(self.id)


class Pedido(models.Model):
    carro = models.OneToOneField(Carro, on_delete=models.CASCADE)
    identificacion_factura = models.CharField('Identificacion Factura', max_length=20, unique=True)
    cedula = models.CharField('Cedula', max_length=10)
    telefono = models.CharField('Telefono', max_length=10,null=True)
    direccion = models.CharField('Direccion', max_length=30,)
    pedido_por = models.CharField(max_length=100)
    subtotal = models.PositiveIntegerField()
    descuento = models.PositiveIntegerField()
    total = models.PositiveIntegerField(null=True, blank=True)
    creado_el = models.DateField(auto_now_add=True)

    objects = VentasManager()

    def __str__(self):
        return "Pedido: " + str(self.id) + ' - ' + 'Fecha: ' + str(self.creado_el) 

    
    


   

apps/ventas/forms.py
from tkinter import Widget
from django import forms
from django.forms import Textarea, TextInput, NumberInput

from .models import Producto, Pedido


class ProductoRegisterForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('identificacion','nombre', 'descripcion', 'precio', 'iva', 'stock', 'vendedor')
        widgets = {
            'identificacion':forms.NumberInput(),
            'nombre': forms.TextInput(),
            'descripcion': forms.Textarea(attrs={'cols': 20, 'rows': 2, 'style':'resize:none;', 'id':'descripcionInput'}),
            'precio': forms.NumberInput(),
            'iva': forms.NumberInput(),
            'stock': forms.NumberInput(),
            'vendedor': forms.Select()
        }

    def clean(self):
        cleaned_data = super(ProductoRegisterForm, self).clean
        identificacion = self.cleaned_data['identificacion']
        
        if Producto.objects.filter(identificacion=identificacion).exists():
            print('entre en el if vendedor')
            raise forms.ValidationError("Este id ya a sido registrado")
        
        return self.cleaned_data

        


class FacturaForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = (
            'identificacion_factura',
            'pedido_por',
            'cedula',
            'telefono',
            'direccion'
        )
        widgets = {
            'identificacion_factura':forms.TextInput(),
            'pedido_por': forms.TextInput(),
            'cedula': forms.NumberInput(),
            'telefono': forms.NumberInput(),
            'direccion': forms.TextInput(),
        }

apps/ventas/views.py
from multiprocessing import context
from urllib import request
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView,ListView, DeleteView, UpdateView, FormView, View, CreateView

from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Carro, Pedido, Producto, ProductoCarro

from django.contrib.messages.views import SuccessMessageMixin

from .forms import FacturaForm, ProductoRegisterForm

import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.template import Context
# Create your views here.

#Views del apartado ventas


class ProductoCreateView(PermissionRequiredMixin, SuccessMessageMixin, FormView):
    form_class = ProductoRegisterForm
    template_name = 'ventas/formulario.html'
    success_url = '.'
    permission_required = 'ventas.add_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')
    success_message = 'El registro fue agregado con exito'

    #validacion de los datos
    def form_valid(self, form):
        
        Producto.objects.create(
            identificacion = form.cleaned_data['identificacion'],
            nombre = form.cleaned_data['nombre'],
            descripcion = form.cleaned_data['descripcion'],
            precio = form.cleaned_data['precio'],
            iva = form.cleaned_data['iva'],
            stock = form.cleaned_data['stock'],
            vendedor = form.cleaned_data['vendedor'],
        )
    
        return super(ProductoCreateView, self).form_valid(form)
    

class ListaProductosViewTrg(PermissionRequiredMixin, ListView):
    template_name = 'ventas/ventas.html'
    model = Producto
    paginate_by = 5
    ordering = 'nombre'
    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword","")

        
        return Producto.objects.listar_producto_trg(palabra_clave)


class ProductoUpdateView(PermissionRequiredMixin, UpdateView):
    model = Producto
    template_name = "ventas/update.html"
    fields = ('__all__')
    success_url = reverse_lazy('ventas_app:ventas')
    permission_required = 'ventas.change_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')


class ProductoDeleteView(PermissionRequiredMixin, DeleteView):
    model = Producto
    success_url = reverse_lazy('ventas_app:ventas')
    permission_required = 'ventas.delete_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')


class FacturasView(PermissionRequiredMixin, ListView):
    template_name = 'ventas/facturas.html'
    model = Pedido
    paginate_by = 5
    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get_queryset(self):
        #aqui obtengo el input del html a traves de un get
        palabra_clave = self.request.GET.get("kword", "")
        lista = Pedido.objects.filter(
            #Buscamos por cadena, ejemplo= si buscamos jo el icontains se encargara de buscar todos los nombres
            #que contangan la j y la o al principio
            cedula__icontains=palabra_clave
        )
        return lista

class Error403View(TemplateView):
    template_name = 'ventas/error403.html'


#------------------------------------------------Logica carrito de ventas/facturacion ----------------------------------

class AgregarAlCarro(PermissionRequiredMixin, TemplateView):
    template_name = 'ventas/agregarCarro.html'
    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #obtener id del producto desde la peticion de url
        product_id = self.kwargs['pro_id']

        #obtener el producto
        product_obj = Producto.objects.get(id=product_id)

        #comprobar si el carro existe
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart_obj = Carro.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.productocarro_set.filter(producto=product_obj)

            #producto ya existente en el carro
            if this_product_in_cart.exists():
                productocarro= this_product_in_cart.last()
                productocarro.cantidad += 1
                productocarro.subtotal += product_obj.precio
                productocarro.save()
                cart_obj.total += product_obj.precio
                cart_obj.save()
                
            #nuevo producto es agregado en el carro
            else:
                productocarro = ProductoCarro.objects.create(
                    carro=cart_obj, producto=product_obj, rate=product_obj.precio, cantidad=1,
                    subtotal=product_obj.precio
                )
                cart_obj.total += product_obj.precio
                cart_obj.save()
        else:
            cart_obj = Carro.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            productocarro = ProductoCarro.objects.create(
                    carro=cart_obj, producto=product_obj, rate=product_obj.precio, cantidad=1,
                    subtotal=product_obj.precio
                )
            cart_obj.total += product_obj.precio
            cart_obj.save()
           
        return context 


class EditarCarroView(PermissionRequiredMixin, View):

    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs['cp_id']
        action = request.GET.get("action")
        cp_obj = ProductoCarro.objects.get(id=cp_id)
        cart_obj = cp_obj.carro
        
        if action == 'inc':
            cp_obj.cantidad += 1
            cp_obj.subtotal += cp_obj.rate
            cp_obj.save()
            cart_obj.total += cp_obj.rate
            cart_obj.save()
        elif action == 'dcr':
            cp_obj.cantidad -= 1
            cp_obj.subtotal -= cp_obj.rate
            cp_obj.save()
            cart_obj.total -= cp_obj.rate
            cart_obj.save()
            if cp_obj.cantidad == 0:
                cp_obj.delete()

        elif action == 'rmv':
            cart_obj.total -= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()

        else:
            pass
        return redirect('ventas_app:MiCarro')


class VaciarCarroView(View):
    def get(self, request, *args, **kwargs):
        cart_id = request.session.get('cart_id', None)
        if cart_id:
            cart = Carro.objects.get(id=cart_id)
            cart.productocarro_set.all().delete()
            cart.total = 0
            cart.save()

        return redirect('ventas_app:MiCarro')




class CarroView(PermissionRequiredMixin, TemplateView):
    template_name = 'ventas/mycart.html'
    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart = Carro.objects.get(id=cart_id)
        else:
            cart = None

        context['carro'] = cart     
        return context


class FacturacionView(PermissionRequiredMixin, CreateView):
    template_name = 'ventas/facturacion.html'
    form_class = FacturaForm
    success_url = reverse_lazy('ventas_app:ventas')
    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart_obj = Carro.objects.get(id=cart_id)
        else:
            cart_obj = None

        context['carro'] = cart_obj

        return context

    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id')
        if cart_id:
            cart_obj = Carro.objects.get(id=cart_id)
            form.instance.carro = cart_obj
            form.instance.subtotal = cart_obj.total
            form.instance.descuento = 0
            form.instance.total = cart_obj.total
            del self.request.session['cart_id']
        else:
            return redirect('ventas_app:ventas')
        return super().form_valid(form)

#------------------------------------------Fin Logica carrito de ventas/facturacion----------------------------------


#------------------------------------------Modulo de reportes--------------------------------------------------------

#Top 10 productos mas vendidos
class Reporte10PMV(PermissionRequiredMixin, View):

    permission_required = 'ventas.view_producto'
    permission_denied_message = 'No tienes permisos'
    login_url = reverse_lazy('user_app:login')

    def get(self, request, *args, **kwargs):

        sqlquery = ''' select vp.id, vp.nombre, sum(vpc.cantidad)
            from ventas_productocarro vpc inner join ventas_producto vp on vpc.producto_id = vp.id
            group by vp.id, vp.nombre
            order by sum(vpc.cantidad) desc limit 10
        '''

        productocarro = ProductoCarro.objects.raw(sqlquery)


        try:
            template = get_template('ventas/reporteProductoPDF.html')

templates/ventas/agregarCarro.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Carro
{% endblock title %}
{% block content %}
    <h1>Producto agregado al carro</h1>
{% endblock content %}

templates/ventas/delete.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Eliminar Producto{% endblock title %}
{% block content %}

<!--
<form method="post">{% csrf_token %}
    <h3>¿Quiere eliminar este profucto? {{ producto.nombre }}</h3>
        <p >confirme que desea eliminar</p>
        <button type="submit">Confirmar</button>      
</form>
-->
<link rel="stylesheet" href="{% static 'styles/delete.css' %}">


{% endblock content %}

templates/ventas/error403.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/styles/home.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="/static/styles/error403.css">
    <title>Error</title>
</head>
<body>
    <div class="error">
            <div class="texto">
                <h1>No esta autorizado para acceder a este modulo...</h1><br>
                <h2>Por favor, comuniquese con el administrador o un superior. </h2><br><br>
                <a href="{% url 'veterinaria_app:home' %}">Volver al Inicio de la Veterinaria</a>
            </div>
    
            <div class="imagen-content">
                <img class="imagen" src="/static/assets/Sad-Cat.png" alt="Gato tristón">
            </div>
    </div>
    
</body>
</html>

templates/ventas/facturacion.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Facturacion
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="/static/styles/facturacion.css">
<div class="container">
    <div class="col1">
        <p class="producto"> Productos en el carro </p>
        <a class="actCarro" href="{% url 'ventas_app:MiCarro' %}">Actualizar carro</a>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {% for c in carro.productocarro_set.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ c.producto.nombre }}</td>
                    <td>{{ c.rate }}</td>
                    <td>{{ c.cantidad }}</td>
                    <td>{{ c.subtotal }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th class="total">Total: {{ carro.total }} </th>                    
                </tr>
            </tbody>
        </table>
    </div>
    <br>
    <div class="col2">
        <p class="factura" >Generar Factura </p>
        <form action="" method="post">
            {% csrf_token %}
            <div class="campo">
                <label class="idFactura">Id factura:</label>
                {{ form.identificacion_factura }}
            </div>
            <div class="campo">
                <label class="pedidoP" >Pedido por:</label>
                {{ form.pedido_por }}
            </div>
            <div class="campo">
                <label class="cde">Cedula:</label>
                {{ form.cedula }}
            </div>
            <div class="campo">
                <label class="tele">Telefono:</label>
                {{ form.telefono }}
            </div>
            <div class="campo">
                <label class="direc">Direccion:</label>
                {{ form.direccion }}
            </div>
            <button type="submit">Continuar</button>
            <img class="imagen" src="/static/assets/factura.png" alt="">
        </form>
    </div>
</div>

{% endblock content %}

templates/ventas/facturas.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/ventas.css' %}">
<script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Facturas</h2>
      <nav class="btn">
      </nav>
    </section>
     <table>
       <thead>
         <tr class="propiedad">
           <th>ID</th>
           <th>Cedula</th>
           <th>Cliente</th>
           <th>Fecha</th>
           <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for p in object_list %}
          <tr id="valores">
            <td>{{ p.identificacion_factura|truncatechars:30 }}</td>
            <td>{{ p.cedula|truncatechars:30 }}</td>
            <td>{{ p.pedido_por|truncatechars:20 }}</td>
            <td>{{ p.creado_el|truncatechars:20 }}</td>
            <td>{{ p.total|truncatechars:20 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>


<!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
    
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><b>&laquo;</b></a>  
    {% endif %}
    
    {% for pagina in paginator.page_range %}
    {% if pagina == page_obj.number  %}
    <a class="active" href="?page={{ pagina }}"><b>{{ pagina }}</b></a>
    {% else %}
    <a href="?page={{ pagina }}"><b>{{ pagina }}</b></a> 
    {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><b>&raquo;</b></a>   
    {% endif %}
    
    {% endif %}
    
  </div>
</div>
  <!-- FIN bloque de paginacion -->

  <script src="{% static 'scripts/ventas.js' %}"></script>

      
      
{% endblock content %}
      

templates/ventas/mycart.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Mi Carro
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="/static/styles/myCart.css">
<div class="container">
    <div class="row">
        <p class="itemsCar">Items en mi carro <p>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                    <th>Accion</th>
                </tr>
            </thead>
            <tbody>
                {% for c in carro.productocarro_set.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ c.producto.nombre }}</td>
                    <td>{{ c.rate }}</td>
                    <td>{{ c.cantidad }}</td>
                    <td>{{ c.subtotal }}</td>
                    <td>
                        <a class="mas" href="{% url 'ventas_app:EditarCarro' c.id %}?action=inc">+</a>
                        <a class="menos" href="{% url 'ventas_app:EditarCarro' c.id %}?action=dcr">-</a>
                        <a class="multi" href="{% url 'ventas_app:EditarCarro' c.id %}?action=rmv">x</a>
                    </td>
                </tr>
                {% endfor %}
                <tr>

                    <td class="total1">
                        <p class="total">Total:</p>
                        <p class="carroTotal">{{ carro.total }}</p>
                        {% if carro.productocarro_set.all %}
                        <p class="vaciarCarro"><a href="{% url 'ventas_app:VaciarCarro' %}">Vaciar Carro</a></p>
                        {% endif %}
                    </td>
                </tr>
                    {% if carro.productocarro_set.all %}
                <td class="generar">
                    <p class="generarFac"><a href="{% url 'ventas_app:Facturacion' %}">Generar Factura</a></p>
                </td>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

templates/ventas/reporteCompradorPDF.html
<style>
    table, th, td{
        border: 1px solid black;
    }
</style>

<table>
    <thead>
        <th>#</th>
        <th>Nombre</th>
        <th>Cantidad Comprada</th>
    </thead>
    <tbody>
        <h1>{{ title }}</h1>
        {% for c in compradores %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ c.pedido_por }}</td>
            <td>{{ c.count }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/ventas/reporteProductoPDF.html
<style>
    table, th, td{
        border: 1px solid black;
    }
</style>

<table>
    <thead>
        <th>Id</th>
        <th>Nombre</th>
        <th>Cantidad Vendida</th>
    </thead>
    <tbody>
        <h1>{{ title }}</h1>
        {% for p in productocarro %}
        <tr>
            <td>{{ p.id }}</td>
            <td>{{ p.nombre }}</td>
            <td>{{ p.sum }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/ventas/ventas.html
{% extends 'index.html' %}
{% load static%}
{% block title %}Dashboard
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles/ventas.css' %}">
  <script src="https://kit.fontawesome.com/7fed639e7f.js" crossorigin="anonymous"></script>
    <section class="header">
      <h2 class="ventas">Inventario</h2>
       <nav class="btn">
          <a class="agregar" href="{% url 'ventas_app:MiCarro' %}"><i class="fa-solid fa-cart-arrow-down"></i>Carro</a>
          <a class="agregar" href="{% url 'ventas_app:formulario' %}"><i class="fa-solid fa-plus"></i>Agregar</a>
        </nav>
    </section>
    <form method="get">
    <div class="buscar">
        {% csrf_token %}
        <input type="text" name="kword" class="t" id="kword" placeholder="Ingrese el nombre">
        <button class="lupa" type="submit"><img src="/static/assets/lupa.png"></button> 
      </div>
    </form>
    <br>
    <br>
     <table>
       <thead>
         <tr class="propiedad">
           <th>Identificacion</th>
           <th>Nombre</th>
           <th>Descripcion</th>
           <th>Precio</th>
           <th>Iva</th>
           <th>Stock</th>
           <th>Accion</th>
          </tr>
        </thead>
        <tbody>
          
          {% for p in object_list %}
          <tr id="valores">
            <td>{{ p.identificacion|truncatechars:30 }}</td>
            <td>{{ p.nombre|truncatechars:30 }}</td>
            <td>{{ p.descripcion|truncatechars:30 }}</td>
            <td>{{ p.precio|truncatechars:20 }}</td>
            <td>{{ p.iva|truncatechars:20 }}</td>
            <td>{{ p.stock|truncatechars:20 }}</td>
            <td>
              <a class="fa-solid fa-crop" href="{% url 'ventas_app:update' p.id %}"></a>
              <a class="fa-regular fa-trash-can" href="javascript:abrir()"></a>
              <a class="fa-solid fa-cart-shopping" href="{% url 'ventas_app:agregarCarro' p.id %}"></a>
            </td>
          </tr>
          
          
            <div class="Ventanae" id="elimi">
              <form action="{% url 'ventas_app:delete' p.id %}" method="post">
                {% csrf_token %}
                <h3>¿Quiere eliminar este producto? </h3>
                <h3>{{ p.nombre }}</h3>
                <h3>confirme que desea realizar</p>
                  <br>
                  <button type="submit" id="Confirmar">Confirmar</button>
                </form>
                <button id="cancelar" onclick="cerrar()"> Cancelar</button>
            </div>

            {% empty %}
                <div class="alert">
                  <span span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  No se han encontrado resultados.
                </div>

            
          {% endfor %}
        </tbody>
      </table>
      <script src="{% static 'scripts/ventas.js' %}"></script>

      <!-- inicio de bloque de paginacion -->
<div class="center">

  <div class="pagination">
    
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><b>&laquo;</b></a>  
    {% endif %}
    
    {% for pagina in paginator.page_range %}
    {% if pagina == page_obj.number  %}
    <a class="active" href="?page={{ pagina }}"><b>{{ pagina }}</b></a>
    {% else %}
    <a href="?page={{ pagina }}"><b>{{ pagina }}</b></a> 
    {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><b>&raquo;</b></a>   
    {% endif %}
    
    {% endif %}
    
  </div>
</div>
  <!-- FIN bloque de paginacion -->
  
  
  
{% endblock content %}
      