apps/users/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    
    path('login-user/',views.LoginUser.as_view(),name='login'),
    path('registrar-vendedor/',views.VendedorRegisterView.as_view(),name='registrar-vendedor'),
    path('registrar-veterinario/',views.VeterinarioRegisterView.as_view(),name='registrar-veterinario'),
    path('registrar-admin/',views.AdminRegisterView.as_view(),name='registrar-admin'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    
    path('administrador/',views.ListViewAdministrador.as_view(),name='administrador'),
    path('registrarUsuariosHome/',views.HomeRegistrarUsuarios.as_view(),name='registrarUsuariosHome'),
    path('home-listado/',views.HomeVerUsuarios.as_view(),name='homeListado'),

    path('ver-admins/',views.ListViewVerAdmins.as_view(),name='verAdmins'),
    path('actualizar-admins/<pk>/',views.AdminUpdateView.as_view(),name='actualizarAdmins'),
    path('eliminar-admins/<pk>/',views.AdminDeleteView.as_view(),name='eliminarAdmins'),

    path('ver-vendedor/',views.ListViewVerVendedores.as_view(),name='verVendedor'),
    path('actualizar-vendedor/<pk>/',views.VendedorUpdateView.as_view(),name='actualizarVendedor'),
    path('eliminar-vendedor/<pk>/',views.VendedorDeleteView.as_view(),name='eliminarVendedor'),

    path('ver-veterinario/',views.ListViewVerVeterinario.as_view(),name='verVeterinario'),
    path('actualizar-veterinario/<pk>/',views.VeterinarioUpdateView.as_view(),name='actualizarVeterinario'),
    path('eliminar-veterinario/<pk>/',views.VeterinarioDeleteView.as_view(),name='eliminarVeterinario'),

    path('reporteUsuarios/',views.ListViewReporteUsuarios.as_view(),name='reporteUsuarios'),
]

apps/ventas/urls.py
from django.urls import path
from . import views

app_name = 'ventas_app'
urlpatterns = [
    path('inventario/',views.ListaProductosViewTrg.as_view(),name='ventas'),
    path('formulario/',views.ProductoCreateView.as_view(),name='formulario'),
    path('facturas/',views.FacturasView.as_view(),name='facturas'),
    path('update/<pk>/',views.ProductoUpdateView.as_view(),name='update'),
    path('delete/<pk>/',views.ProductoDeleteView.as_view(),name='delete'),

    path('add-to-cart-<int:pro_id>/',views.AgregarAlCarro.as_view(),name='agregarCarro'),
    path('my-cart/',views.CarroView.as_view(),name='MiCarro'),
    path('editar-carro/<int:cp_id>/',views.EditarCarroView.as_view(),name='EditarCarro'),
    path('empty-car/',views.VaciarCarroView.as_view(),name='VaciarCarro'),

    path('facturacion/',views.FacturacionView.as_view(),name='Facturacion'),

    path('reporte1pdf/',views.Reporte10PMV.as_view(),name='reporteUnoPDF'),
    path('reporte2pdf/',views.Reporte10PMC.as_view(),name='reporteDosPDF'),
    path('reporte3pdf/',views.ReporteRangoFechas.as_view(),name='reporteTres'),
]

apps/veterinario/urls.py
from django.urls import path
from . import views

app_name = 'veterinaria_app'
urlpatterns = [
    path('',views.ListViewVeterinario.as_view(),name='home'),
    path('historial/',views.ListViewHistorial.as_view(),name='historial'),
    path('formulario-historial/',views.CreateFormularioHistorial.as_view(),name='formulario-historial'),
    path('inicio-historial/',views.ListViewInicioHistorial.as_view(),name='inicio-historial'),
    path('cliente-responsable/',views.ListViewVerClienteResponsable.as_view(),name='cliente-responsable'),
    path('formulario-cliente/',views.CreateClienteResponsable.as_view(),name='formulario-cliente'),
    path('mascotas/',views.ListViewMascotas.as_view(),name='mascotas'),
    path('formulario-mascota/',views.CreateFormularioMascotas.as_view(),name='formulario-mascota'),
    path('detalle-historial/<pk>/',views.DetailViewHistorial.as_view(),name='detailView'),

]

veterinariaApp/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls import handler403
from apps.ventas.views import Error403View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.veterinario.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('user/',include('apps.users.urls')),
]

#Manejo de errores
handler403 = Error403View.as_view()

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/static/assets/logo.png">
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
    <!--Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">
    <aside>
        <div class="top">
            <div class="logo">
                <img class="logo" src="/static/assets/logo.png" alt="">
                <h2 class="title">VETERINARIA</h2>
            </div>
            <div class="close" id="close-btn">
                <span class="material-icons-sharp">close</span>
            </div>
        </div>
        <div class="sidebar">
            <a href="{% url 'veterinaria_app:home' %}" class="active inicio opc">
                <span class="material-icons-sharp">
                    grid_view
                </span>
                <h3>Inicio</h3>
            </a>
            <a href="{% url 'veterinaria_app:inicio-historial' %}" class="active historial opc">
                <span class="material-icons-sharp">
                    history
                </span>
                <h3>Historial clinico</h3>
            </a>
            <a href="{% url 'ventas_app:ventas' %}" class="active btn-ventas opc">
                <span class="material-icons-sharp">
                    shopping_cart
                </span>
                <h3>inventario</h3>
            </a>
            <a href="{% url 'user_app:administrador' %}" class="active btn-ventas">
                <span class="material-icons-sharp">
                    admin_panel_settings
                </span>
                <h3>Administrador</h3>
            </a>
            <a href="{% url 'ventas_app:facturas' %}" class="active btn-ventas opc">
                <span class="material-icons-sharp">
                    monetization_on
                </span>
                <h3>Facturas</h3>
            </a>
            <br>
        </div>
    </aside>
    <!--MAIN-->
    <main>
        <div class="insights">
            <div class="sales">
                {% block content %}
                {% endblock content %}    
            </div>
        </div>
    </main>
    <!--FINAL de MAIN-->
    <div class="right">
        <div class="top">         
            <div class="theme-toggler">
                <span class="material-icons-sharp active">
                    light_mode
                </span>
                <span class="material-icons-sharp dark">
                    dark_mode
                </span>
            </div>
            {% if not user.is_anonymous %}
            <a class="salir" href="{% url 'user_app:logout' %}">
                <span class="material-icons-sharp">
                    logout
                </span>
                <h4>Salir</h4>
            </a>
            <div class="profile">
                <div class="info">
                    <p>Bienvenido<b class="user"></b></p>
                    <small class="text-muted">{{ user.correo }}</small>
                </div>
            {% else %} 
                <div class="profile-photo">
                    <a href="{% url 'user_app:login' %}"><img src="{% static 'assets/user.png' %}"></img></button>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<script src="{% static 'scripts/home.js' %}"></script>
</body>
</html>